---
# yamllint disable rule:line-length

name: Automatically add issues to project tracking board

on:  # yamllint disable-line rule:truthy
  issues:
    types:
      - opened
      - transferred

jobs:
  add-to-project:
    name: Add issue to project board
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/add-to-project
      - uses: actions/add-to-project@1b844f0c5ac6446a402e0cb3693f9be5eca188c5 # v0.6.1
        with:
          project-url: https://github.com/orgs/backube/projects/1
          # PAT needs repo & project scope
          github-token: ${{ secrets.PAT_WORKFLOW }}
